# This rule is not used by the project managed-postgres-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to managed-postgres-operator.hoppscale.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: managed-postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresrole-viewer-role
rules:
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresroles/status
  verbs:
  - get
