# This rule is not used by the project managed-postgres-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over managed-postgres-operator.hoppscale.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: managed-postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresdatabase-admin-role
rules:
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresdatabases
  verbs:
  - '*'
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresdatabases/status
  verbs:
  - get
