---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresfunctions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresfunctions/finalizers
  verbs:
  - update
- apiGroups:
  - managed-postgres-operator.hoppscale.com
  resources:
  - postgresfunctions/status
  verbs:
  - get
  - patch
  - update
