replicaCount: 1

image:
  repository: ghcr.io/hoppscale/managed-postgres-operator
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
