replicaCount: 1

image:
  repository: ghcr.io/hoppscale/managed-postgres-operator
  pullPolicy: IfNotPresent
  tag: master

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

rbac:
  create: true

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

operatorInstanceName: ""
reconciliationRequeueInterval: ""

extraEnv: []
envFrom: []

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

prometheus:
  enabled: false
  podMonitor:
    enabled: false
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: {}
    annotations: {}
    honorLabels: false
